### ISSUE TITLE
群主, 中文文件夹报错这事, 只能你更新了. 我去官网提交了, 人家说正常....

### ISSUE THREAD

**Issue by nuan1989** [duolabmeng6/goefun#3]
https://github.com/golang/go/issues/52918
我去提交了.  人家说正常....
------------
主要是像我一样不懂英文的新人拉取下来,  第一次运行不起来, 就会认为是库没人维护了, 库有问题. 
其实自己改改文件夹名称就行. 
 
![168510051-5a4aca31-0cd5-4264-abf1-a1860c6910bb](https://user-images.githubusercontent.com/43518669/169854698-fecf44c4-36e0-4a22-a0b0-464230918433.png)

**Comment by Jeff-xu0** [comment]
在不同的平台，unicode字符的显示会有很大出入，所以从1.16开始go给出了unicode限制，回退版本到go1.15即可通过编译  
![企业微信截图_16802335043593](https://user-images.githubusercontent.com/62273098/229015973-27a1d6ab-0da8-4a00-80ba-313d9c4196dc.png)

**Comment by duolabmeng6** [comment]
我最近没空更新啊 你可以下载项目改一下，pr回来就行



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Jeff-xu0 ***@***.***&gt;
发送时间: 2023年3月31日 11:32
收件人: duolabmeng6/goefun ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [duolabmeng6/goefun] 群主, 中文文件夹报错这事, 只能你更新了. 我去官网提交了, 人家说正常.... (Issue #3)





 
在不同的平台，unicode字符的显示会有很大出入，所以从1.16开始go给出了unicode限制，回退版本到go1.15即可通过编译

**Comment by duolabmeng6** [comment]
已更新
